### ISSUE TITLE
Problem authenticating

### ISSUE THREAD

**Issue by KevinMitchell** [hadesbox/raml-api-designer-store#2]
Hi 

I tried following the instructions on setting up the system, and am having problems logging into it.  The server starts up OK.  I then add a user as follows:

Kevins-MacBook-Pro-5:~ kevin$ echo -n test | openssl sha1
a94a8fe5ccb19ba61c4c0873d391e987982fbbd3

And then in mongo I do this

> db.users.insert({"mail":"kevin", "pass":"a94a8fe5ccb19ba61c4c0873d391e987982fbbd3", "admin":true, "team":"tedi", "projects":["test"]});
> WriteResult({ "nInserted" : 1 })
> db.users.find()
> { "_id" : ObjectId("55fa54cc08a56ac1a12361a6"), "mail" : "kevin", "pass" : "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3", "admin" : true, "team" : "tedi", "projects" : [ "test" ] }

But if I try to log into the system running on port 3000 with user kevin and password test it complains about wrong username or password.  As there were a few typos in the "getting started" instructions I'm hoping there's something simple I'm missing in the configuration that explains this behaviour.  Any suggestions?

Thanks,
Kevin

**Comment by beeva-luisgonzalez** [comment]
Hi  Kevin, 
This is a record I have on my mongo:

```
{ "_id" : ObjectId("53d76..."), "mail" : "admin", "pass" : "f688d9....", "admin" : true, "projects" : [ "proyect1", "proyect2" ], "team" : "op" }
```
The only thing I can imagine is that you didn't created the users collection inside the __ramldb__ database.

```
> show dbs
admin   (empty)
local   0.078GB
ramldb  0.078GB
```

by default when you connect to mongo you are in the local database.

The database is hardcoded (yes.. I know sorry)... as __ramldb__ (here)[https://github.com/hadesbox/raml-api-designer-store/blob/4ee2f22ead600c166878336f2a2f913b73659d9a/mongo-http.js#L14] and  [here](https://github.com/hadesbox/raml-api-designer-store/blob/4ee2f22ead600c166878336f2a2f913b73659d9a/routes/files.js#L8]), try creating the collection users inside the ramldb database.

Let me know if you have more input from the console or any problems.. and sorry for the poor documentation!

**Comment by KevinMitchell** [comment]
Thanks for the suggestion Luis,

Unfortunately when I type

db.getName()

I get back ramldb

So it doesn’t look like that’s the problem.  

Ah, I tried restarting the server and it now authenticates;  I have no idea why.  But at least the problem seems to have gone away.

Thanks for your help,

Kevin

**Comment by hadesbox** [comment]
great then I'm closing this, don't hesitate to send any questions! I'll help if can.

**Comment by hadesbox** [comment]
Ohh and BTW check the admin tool I made to manage users and projects (it was a pain to do it with mongo queries because we have more than 40 users of this RAML server, with several projects), It's located at [admintools](https://github.com/hadesbox/raml-api-designer-store/tree/master/admintool)

__exportprojects__ will download all RAML files from the mongodb and create them as a folder structure in /tmp.

__ramladmin__ will let you create add remove users and projects
